name: nuha
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  google_fonts: 4.0.3
  simple_gradient_text: 1.2.4
  font_awesome_flutter: 10.4.0
  firebase_auth: ^4.2.10
  cloud_firestore: ^4.4.4
  firebase_storage: ^11.0.15
  firebase_core: ^2.7.1
  zoom_tap_animation: 1.1.0
  iconify_flutter: 0.0.5
  flutter: 
    sdk: flutter
  get_storage: ^2.1.1
  sizer: ^2.0.15
  intl: ^0.17.0
  google_sign_in: ^6.0.2
  iconify_flutter: ^0.0.5
  image_picker: ^0.8.7+1
  badges: ^3.0.3  
  chips_choice: ^3.0.0
  http: ^0.13.5
  timeago: ^3.3.0
  intl_utils: ^2.8.2
  flutter_localization: ^0.1.10

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
    - assets/icons/
  uses-material-design: true

